blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/liijamiilmfs/gpt-task-runner/security/advisories/new
    about: Please use this to report security issues privately.
